"""Generate a source-data-backed main figure for the audited candidate release.

The figure makes no external-validation claim. It visualizes only the frozen
candidate-status audit, three-model probability concordance, and the closest-
labelled-homolog strata generated by the publication pipeline.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
RESOURCE = ROOT / "results" / "tpc_candidate_resource"
OUT = ROOT / "results" / "manuscript_figures" / "figure6_audited_candidate_resource"

COLORS = {
    "known_label_used_in_study": "#2B5C8A",
    "pseudo_label_used_in_study": "#91A7C0",
    "phenotype_recorded_but_excluded": "#D59A3A",
    "true_unknown_candidate": "#4D8A69",
    "single": "#213E63",
    "joint": "#7A5AA6",
    "annotation": "#C56A4D",
    "isolated": "#5A9A7A",
    "supported": "#845FA4",
}


def configure() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "font.size": 7,
            "axes.linewidth": 0.7,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "pdf.fonttype": 42,
            "svg.fonttype": "none",
        }
    )


def add_panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(-0.15, 1.08, label, transform=ax.transAxes, fontsize=11, fontweight="bold", va="top")


def status_panel(ax: plt.Axes, release: dict[str, pd.DataFrame]) -> pd.DataFrame:
    order = [
        "known_label_used_in_study",
        "pseudo_label_used_in_study",
        "phenotype_recorded_but_excluded",
        "true_unknown_candidate",
    ]
    summary_rows = []
    for species, frame in release.items():
        counts = frame["candidate_status"].value_counts()
        for status in order:
            summary_rows.append({"species": species, "candidate_status": status, "genes": int(counts.get(status, 0))})
    summary = pd.DataFrame(summary_rows)
    bottom = np.zeros(2)
    species_labels = ["Arabidopsis", "Rice"]
    for status in order:
        values = [summary.loc[(summary.species == species) & (summary.candidate_status == status), "genes"].iloc[0] for species in ["arabidopsis", "rice"]]
        ax.bar(range(2), values, bottom=bottom, width=0.62, color=COLORS[status], edgecolor="white", linewidth=0.6, label=status.replace("_", " "))
        bottom += np.asarray(values)
    ax.set_xticks(range(2), species_labels)
    ax.set_ylabel("Feature-covered genes")
    ax.set_title("Audited release status", loc="left", fontweight="bold")
    ax.set_ylim(0, max(bottom) * 1.12)
    for x, total in enumerate(bottom):
        ax.text(x, total + max(bottom) * 0.025, f"{int(total):,}", ha="center", va="bottom", fontsize=7)
    ax.legend(loc="upper left", fontsize=5.2, handlelength=1.0, frameon=False)
    return summary


def concordance_panel(ax: plt.Axes, candidates: pd.DataFrame, species_label: str) -> pd.DataFrame:
    candidates = candidates.sort_values("final_core_candidate_rank").copy()
    x = np.arange(len(candidates))
    values = {
        "single": pd.to_numeric(candidates["single_species_probability"]),
        "joint": pd.to_numeric(candidates["joint_probability"]),
        "annotation": pd.to_numeric(candidates["annotation_light_probability"]),
    }
    offsets = [-0.18, 0, 0.18]
    labels = {"single": "single-species", "joint": "joint", "annotation": "annotation-light"}
    for index, key in enumerate(["single", "joint", "annotation"]):
        ax.scatter(x + offsets[index], values[key], s=19, color=COLORS[key], label=labels[key], zorder=3, linewidths=0)
        ax.plot(x + offsets[index], values[key], color=COLORS[key], alpha=0.42, linewidth=0.8, zorder=2)
    ax.axhline(0.5, color="#6E6E6E", linewidth=0.65, linestyle="--", zorder=1)
    ax.set_ylim(0.25, 1.03)
    ax.set_ylabel("Essentiality probability")
    ax.set_xticks(x, candidates["gene_id"], rotation=55, ha="right", fontsize=5.5)
    ax.set_title(f"{species_label} core candidates", loc="left", fontweight="bold", pad=10)
    return candidates[["gene_id", "single_species_probability", "joint_probability", "annotation_light_probability", "homology_category"]]


def homology_panel(ax: plt.Axes, candidates: dict[str, pd.DataFrame]) -> pd.DataFrame:
    categories = ["homology_isolated", "homology_supported_by_essential"]
    rows = []
    for species, frame in candidates.items():
        for category in categories:
            rows.append({"species": species, "homology_category": category, "candidates": int(frame["homology_category"].eq(category).sum())})
    table = pd.DataFrame(rows)
    x = np.arange(2)
    isolated = table.loc[table.homology_category.eq("homology_isolated"), "candidates"].to_numpy()
    supported = table.loc[table.homology_category.eq("homology_supported_by_essential"), "candidates"].to_numpy()
    ax.bar(x, isolated, color=COLORS["isolated"], width=0.62, label="homology-isolated")
    ax.bar(x, supported, bottom=isolated, color=COLORS["supported"], width=0.62, label="supported by labelled essential homolog")
    ax.set_xticks(x, ["Arabidopsis", "Rice"])
    ax.set_ylim(0, 11.5)
    ax.set_ylabel("Core candidates")
    ax.set_title("Closest-labelled-homolog audit", loc="left", fontweight="bold")
    for ix, total in enumerate(isolated + supported):
        ax.text(ix, total + 0.25, f"n = {int(total)}", ha="center", fontsize=7)
    ax.legend(loc="upper left", fontsize=5.8)
    return table


def main() -> None:
    configure()
    OUT.mkdir(parents=True, exist_ok=True)
    release = {
        species: pd.read_csv(
            ROOT / "predictions" / "publication_release" / f"{species}_all_feature_covered_genes_reclassified.tsv",
            sep="\t",
            low_memory=False,
        )
        for species in ["arabidopsis", "rice"]
    }
    candidates = {
        species: pd.read_csv(RESOURCE / f"{species}_final_core10_candidates.tsv", sep="\t")
        for species in ["arabidopsis", "rice"]
    }
    fig = plt.figure(figsize=(7.15, 5.45), layout="constrained")
    grid = fig.add_gridspec(2, 2, height_ratios=[0.95, 1.25], width_ratios=[1.0, 1.24])
    ax_a = fig.add_subplot(grid[0, 0])
    ax_b = fig.add_subplot(grid[0, 1])
    ax_c = fig.add_subplot(grid[1, 0])
    ax_d = fig.add_subplot(grid[1, 1])
    source_a = status_panel(ax_a, release)
    source_b = concordance_panel(ax_b, candidates["arabidopsis"], "Arabidopsis")
    source_c = concordance_panel(ax_c, candidates["rice"], "Rice")
    source_d = homology_panel(ax_d, candidates)
    add_panel_label(ax_a, "a")
    add_panel_label(ax_b, "b")
    add_panel_label(ax_c, "c")
    add_panel_label(ax_d, "d")
    ax_b.legend(loc="upper left", fontsize=5.4, ncol=3, frameon=False)
    fig.savefig(OUT / "Figure6_audited_candidate_resource.svg", bbox_inches="tight")
    fig.savefig(OUT / "Figure6_audited_candidate_resource.pdf", bbox_inches="tight")
    fig.savefig(OUT / "Figure6_audited_candidate_resource.tiff", dpi=600, bbox_inches="tight")
    fig.savefig(OUT / "Figure6_audited_candidate_resource.png", dpi=600, bbox_inches="tight")
    pd.concat(
        [
            source_a.assign(panel="a"),
            source_b.assign(panel="b", species="arabidopsis"),
            source_c.assign(panel="c", species="rice"),
            source_d.assign(panel="d"),
        ],
        ignore_index=True,
        sort=False,
    ).to_csv(OUT / "Figure6_source_data.tsv", sep="\t", index=False)
    plt.close(fig)
    print(f"Wrote Figure 6 to {OUT}")


if __name__ == "__main__":
    main()
