"""Update the Nature-style manuscript with released code, data and web access.

The document edit is deliberately narrow: it preserves the existing tables and
reference list while replacing submission placeholders and adding reproducible
web-server descriptions. It also swaps the first four embedded figures for the
compact publication-style versions generated by generate_nature_figures.py.
"""
from __future__ import annotations

import shutil
import tempfile
import zipfile
from copy import deepcopy
from pathlib import Path

from docx import Document
from docx.shared import Inches
from docx.oxml import OxmlElement


SOURCE = Path("C:/Users/tly/Downloads/Plant_essential_gene_prediction_manuscript_revised_Nature_style (2).docx")
OUTPUT = Path("C:/Users/tly/Downloads/Plant_essential_gene_prediction_manuscript_web_deployment_Nature_style.docx")
FIGURES = Path("C:/Users/tly/Downloads/plantessentialgene_nature_figures")


def insert_after(paragraph, text: str, style: str) -> object:
    new = OxmlElement("w:p")
    paragraph._p.addnext(new)
    new_para = paragraph._parent.add_paragraph()
    new_para._p.getparent().remove(new_para._p)
    new_para._p = new
    new_para._element = new
    new_para.style = style
    new_para.add_run(text)
    return new_para


def replace_exact(doc: Document, old: str, new: str) -> None:
    for paragraph in doc.paragraphs:
        if paragraph.text == old:
            paragraph.text = new
            return
    raise RuntimeError(f"Could not find paragraph: {old[:80]}")


def update_text(doc: Document) -> None:
    abstract_old = (
        "These results provide a transparent framework for plant essential-gene candidate prioritization while emphasizing label uncertainty, annotation bias and the need for experimental validation."
    )
    abstract_new = (
        "These results provide a transparent framework for plant essential-gene candidate prioritization while emphasizing label uncertainty, annotation bias and the need for experimental validation. To enable reuse, we provide the PlantEssentialGenePredictor web system, processed feature resources, trained models and reproducible analysis code."
    )
    for paragraph in doc.paragraphs:
        if abstract_old in paragraph.text:
            paragraph.text = paragraph.text.replace(abstract_old, abstract_new)

    replace_exact(
        doc,
        "Figure 1. Overview of the plant essential-gene prediction framework. The base-learner panel is schematic: the implementation used tree- and boosting-based base learners, five-fold out-of-fold predictions and a logistic-regression meta-learner. All trainable preprocessing was fitted within training folds to avoid data leakage.",
        "Figure 1. Leakage-aware framework for plant essential-gene prediction. One longest protein-coding transcript was retained per gene. The common feature space combined 95 biological features and 6,656 protein language model dimensions. Preprocessing and supervised selection were fitted within training folds; four base learners generated five-fold out-of-fold predictions for logistic-regression stacking."
    )
    replace_exact(
        doc,
        "Figure 2. Main fixed-test predictive performance. (a) AUC and AUPRC summary for single-species models and the joint Arabidopsis-rice model evaluated on each species. (b) ROC curves and (c) precision-recall curves were computed directly from locked fixed-test predictions.",
        "Figure 2. Locked fixed-test performance. (a) AUC and AUPRC for species-specific models and the joint Arabidopsis-rice model evaluated on each species. (b) Receiver-operating-characteristic curves. (c) Precision-recall curves. Curves were computed directly from locked test-set probabilities."
    )
    replace_exact(
        doc,
        "Figure 3. Complete feature-ablation heatmap. Values are fixed-test AUCs from the complete ablation table. Columns distinguish single-species models from the joint Arabidopsis-rice model evaluated on rice or Arabidopsis. The full Arabidopsis row reflects the ablation-refit pipeline and is therefore close to, but not identical with, the locked primary Table 2 Arabidopsis AUC.",
        "Figure 3. Feature-ablation controls. Fixed-test AUCs for the full representation, biological features alone, all PLM embeddings alone, and models without GO or PPI features. The Arabidopsis full-model point (0.9203) is the ablation-refit estimate and is therefore close to, but not identical with, the locked primary estimate in Table 2 (0.9175)."
    )
    replace_exact(
        doc,
        "Figure 4. Leakage-resistance and statistical comparison. (a) Fixed-split AUC compared with homology-cluster grouped AUC. (b) Paired DeLong AUC differences. Positive values indicate higher AUC for the reference model in each comparison; only the Arabidopsis joint-versus-auxiliary comparison was significant after FDR correction.",
        "Figure 4. Homology-aware evaluation and paired model comparison. (a) Fixed-split AUC compared with homology-cluster grouped AUC. (b) Paired DeLong comparison of species-specific and joint models on the same test genes. Positive values indicate higher AUC for the species-specific model; neither comparison was significant after false-discovery-rate correction."
    )

    availability_old = (
        "Submission placeholder - replace before journal submission: processed labels, fixed train/validation/test splits, feature lists, prediction outputs and model-training scripts will be released in a public GitHub repository and archived with a permanent Zenodo, Figshare or OSF DOI. The final statement should include the repository URL, release tag or commit hash, archive DOI and a description of included labels, splits, feature matrices, prediction files and figure-generation scripts. Local development paths are intentionally excluded from the manuscript text."
    )
    availability_new = (
        "Code, processed label tables, fixed train/validation/test splits, feature lists, trained model assets, genome-scale prediction tables and figure-generation scripts are available from GitHub (https://github.com/tianluyao1024/PlantEssentialGenePredictor). Large processed feature matrices and released prediction resources are archived in Zenodo (https://doi.org/10.5281/zenodo.21387076). The interactive PlantEssentialGenePredictor web system is available at https://plantessentialgene.com. Third-party raw resources are not redistributed; the repository documents their original sources and provides feature-extraction workflows."
    )
    replace_exact(doc, availability_old, availability_new)

    replace_exact(
        doc,
        "The reference list was restricted to publications or database papers that could be matched to public indexed records or official database/publication pages. RiceData/manual phenotype tables and TRIM/T-DNA-derived sources are retained in the source audit because they were part of project diagnostics, but they are not cited as primary rice-model sources unless a final public source and exact citation are selected before submission. The Data and code availability section intentionally remains a submission placeholder because no public repository URL, release tag or DOI has yet been provided.",
        "The reference list was restricted to publications or database papers that could be matched to public indexed records or official database/publication pages. RiceData/manual phenotype tables and TRIM/T-DNA-derived sources are retained in the source audit because they were part of project diagnostics, but they are not cited as primary rice-model sources unless a final public source and exact citation are selected before submission. Code, processed resources and model assets are released through the GitHub repository and Zenodo archive stated in the Data and code availability section.",
    )

    after_caption = next(p for p in doc.paragraphs if p.text.startswith("Figure 1. Leakage-aware framework"))
    p = insert_after(after_caption, "A web-accessible predictor supports reusable candidate ranking", "Heading 2")
    insert_after(
        p,
        "To make the released models accessible beyond the two benchmark species, we implemented PlantEssentialGenePredictor as a public Streamlit application (https://plantessentialgene.com). The default workflow is raw biological-file upload, whereas the Arabidopsis single-species, rice single-species and joint full models are available through an advanced processed-feature route. The raw-upload workflow provides nine deployable joint-model feature profiles, spanning sequence plus PLM features alone and the available combinations of GO, PPI and expression summaries. This design separates missing annotation from biological absence rather than treating unobserved GO, PPI or expression values as zero.",
        "Normal",
    )
    p = insert_after(
        p,
        "For raw-data workflows, users upload protein and CDS FASTA files and may add GFF3, GO annotation, PPI edge-list, expression-matrix and domain-annotation files. The interface validates stable gene identifiers across input files, selects one representative transcript per gene, extracts compatible features and returns a downloadable table containing gene identifier, essentiality probability, thresholded class and the selected profile. The web workflow accepts batch execution for long proteomes and provides both online feature extraction and direct use of released processed-feature/model resources.",
        "Normal",
    )

    after_training = next(p for p in doc.paragraphs if p.text.startswith("ROC AUC and AUPRC were threshold-independent"))
    p = insert_after(after_training, "Web-system implementation", "Heading 2")
    insert_after(
        p,
        "The web interface was implemented in Streamlit and deployed at https://plantessentialgene.com. Its raw-upload route accepts CDS FASTA, protein FASTA, optional GFF3, GO, PPI, expression and domain files. FASTA identifiers are harmonized through the first header token; optional tab-separated files must use the same stable gene identifier. GO files contain gene_id and go_id; PPI files contain gene_a, gene_b and score; expression files contain gene_id followed by normalized expression samples; and domain files contain gene_id, domain_id and source. The server calculates sequence-derived features and protein-language-model embeddings in batches, combines available annotations into one of nine released feature profiles, and applies the matched deployed model. Temporary jobs are retained for inspection and can be removed by the server cleanup workflow.",
        "Normal",
    )


def replace_embedded_images(docx: Path) -> None:
    replacements = {
        "word/media/image1.png": FIGURES / "fig1_model_architecture_nature.png",
        "word/media/image2.png": FIGURES / "fig2_main_performance_nature.png",
        "word/media/image3.png": FIGURES / "fig3_feature_ablation_nature.png",
        "word/media/image4.png": FIGURES / "fig4_homology_and_delong_nature.png",
    }
    with tempfile.TemporaryDirectory() as temp_dir:
        temp = Path(temp_dir) / "repacked.docx"
        with zipfile.ZipFile(docx, "r") as source, zipfile.ZipFile(temp, "w", zipfile.ZIP_DEFLATED) as target:
            for item in source.infolist():
                if item.filename in replacements:
                    target.writestr(item, replacements[item.filename].read_bytes())
                else:
                    target.writestr(item, source.read(item.filename))
        shutil.move(temp, docx)


def main() -> None:
    shutil.copy2(SOURCE, OUTPUT)
    doc = Document(OUTPUT)
    update_text(doc)
    # Keep all figures within the document's 7.2-inch printable width and
    # preserve their true aspect ratios after their media parts are replaced.
    sizes = [(6.8, 4.0/7.2*6.8), (6.8, 2.55/7.2*6.8), (6.4, 2.65/7.2*6.4), (6.8, 2.55/7.2*6.8)]
    for shape, (width, height) in zip(list(doc.inline_shapes)[:4], sizes):
        shape.width = Inches(width)
        shape.height = Inches(height)
    doc.save(OUTPUT)
    replace_embedded_images(OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
